-- MySQL Script generated by MySQL Workbench
-- Thu Feb  5 17:01:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupos` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`selecoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`selecoes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`selecoes` (
  `id_selecao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `qtd_copa_vencida` INT NOT NULL DEFAULT 0,
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_selecao`),
  INDEX `fk_selecoes_grupos1_idx` (`id_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_selecoes_grupos1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estadios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estadios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estadios` (
  `id_estadio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cidade` VARCHAR(200) NOT NULL,
  `pais` VARCHAR(200) NOT NULL,
  `capacidade` INT NOT NULL,
  PRIMARY KEY (`id_estadio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`partidas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`partidas` (
  `id_partida` INT NOT NULL AUTO_INCREMENT,
  `id_selecao_a` INT NOT NULL,
  `id_selecao_b` INT NOT NULL,
  `id_estadio` INT NOT NULL,
  `gols_selecao_a` INT NOT NULL DEFAULT 0,
  `gols_selecao_b` INT NOT NULL DEFAULT 0,
  `horario` DATETIME NOT NULL,
  `bilheteria` FLOAT NOT NULL,
  PRIMARY KEY (`id_partida`),
  INDEX `fk_partidas_selecoes1_idx` (`id_selecao_a` ASC) VISIBLE,
  INDEX `fk_partidas_selecoes2_idx` (`id_selecao_b` ASC) VISIBLE,
  INDEX `fk_partidas_estadios1_idx` (`id_estadio` ASC) VISIBLE,
  CONSTRAINT `fk_partidas_selecoes1`
    FOREIGN KEY (`id_selecao_a`)
    REFERENCES `mydb`.`selecoes` (`id_selecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_selecoes2`
    FOREIGN KEY (`id_selecao_b`)
    REFERENCES `mydb`.`selecoes` (`id_selecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_estadios1`
    FOREIGN KEY (`id_estadio`)
    REFERENCES `mydb`.`estadios` (`id_estadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jogadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jogadores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jogadores` (
  `idj_jogador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `n_camisa` INT NOT NULL,
  `n_gol` INT NULL,
  `n_cartao_amarelo` INT NULL,
  `n_cartao_vermelho` INT NULL,
  `faltas_sofrida` INT NULL,
  `faltas_cometida` INT NULL,
  `id_selecao` INT NOT NULL,
  PRIMARY KEY (`idj_jogador`),
  INDEX `fk_jogadores_selecoes_idx` (`id_selecao` ASC) VISIBLE,
  CONSTRAINT `fk_jogadores_selecoes`
    FOREIGN KEY (`id_selecao`)
    REFERENCES `mydb`.`selecoes` (`id_selecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acontecimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`acontecimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`acontecimento` (
  `id_partida` INT NOT NULL,
  `idj_jogador` INT NOT NULL,
  `tipo_acontecimento` VARCHAR(200) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_partida`, `idj_jogador`),
  INDEX `fk_partidas_has_jogadores_jogadores1_idx` (`idj_jogador` ASC) VISIBLE,
  INDEX `fk_partidas_has_jogadores_partidas1_idx` (`id_partida` ASC) VISIBLE,
  CONSTRAINT `fk_partidas_has_jogadores_partidas1`
    FOREIGN KEY (`id_partida`)
    REFERENCES `mydb`.`partidas` (`id_partida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partidas_has_jogadores_jogadores1`
    FOREIGN KEY (`idj_jogador`)
    REFERENCES `mydb`.`jogadores` (`idj_jogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
